import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const sourceDir = path.join(rootDir, 'src', 'data', 'source');
const outputDir = path.join(rootDir, 'src', 'data');

function readCsv(fileName) {
  const filePath = path.join(sourceDir, fileName);
  const text = fs.readFileSync(filePath, 'utf8').replace(/^\uFEFF/, '');
  const rows = parseCsv(text.trim());
  if (rows.length === 0) return [];
  const headers = rows[0];
  return rows.slice(1).filter(row => row.some(cell => cell !== '')).map(row => {
    const record = {};
    headers.forEach((header, index) => {
      record[header] = row[index] ?? '';
    });
    return record;
  });
}

function parseCsv(text) {
  const rows = [];
  let row = [];
  let cell = '';
  let inQuotes = false;

  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    const next = text[index + 1];

    if (char === '"') {
      if (inQuotes && next === '"') {
        cell += '"';
        index += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (char === ',' && !inQuotes) {
      row.push(cell);
      cell = '';
      continue;
    }

    if ((char === '\n' || char === '\r') && !inQuotes) {
      if (char === '\r' && next === '\n') index += 1;
      row.push(cell);
      rows.push(row);
      row = [];
      cell = '';
      continue;
    }

    cell += char;
  }

  row.push(cell);
  rows.push(row);
  return rows;
}

function jsonCell(value, fallback) {
  if (!value) return fallback;
  try {
    return JSON.parse(value);
  } catch (error) {
    throw new Error(`Invalid JSON cell: ${value}\n${error.message}`);
  }
}

function formatJs(value) {
  return JSON.stringify(value, null, 2);
}

function writeFile(fileName, contents) {
  const header = [
    '// This file is generated by `npm run generate:data`.',
    '// Edit source data in src/data/source/*.csv.',
    '// For phrase text, Notion is the canonical editorial source.'
  ].join('\n');
  fs.writeFileSync(path.join(outputDir, fileName), `${header}\n\n${contents.trim()}\n`);
}

function generatePhrases() {
  const phrases = Object.fromEntries(readCsv('phrases.csv').map(row => [
    row.id,
    {
      arabic: row.arabic,
      translation: row.translation,
      literal: row.literal,
      tags: jsonCell(row.tags, [])
    }
  ]));

  writeFile('phrases.js', `
const phrases = ${formatJs(phrases)};

export default phrases;
`);
}

generatePhrases();

console.log('Generated src/data/phrases.js from src/data/source/phrases.csv. Other data modules are hand-edited.');
